/**
 * Created by ming on 2017/2/24
 */
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REQUEST_TOPICS = 'REQUEST_TOPICS';
export const RECEIVE_TOPICS = 'RECEIVE_TOPICS';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const START_ADD_ARTICLE = 'START_ADD_ARTICLE';
export const REQUEST_DETAILS = 'REQUEST_DETAILS';
export const RECEIVE_DETAILS = 'RECEIVE_DETAILS';
export const REQUEST_USERINFO = 'REQUEST_USERINFO';
export const RECEIVE_USERINFO = 'RECEIVE_USERINFO';
export const RECEIVE_USERUPS = 'RECEIVE_USERUPS';
export const PUBLISH_TOPIC = 'PUBLISH_TOPIC ';

//新建评论
export const USER_ADDCOMMENT = 'USER_ADDCOMMENT';
